A	docs/decisions/C1-启动与世界坐标约定.md
A	docs/development/开发1/开发1-岗位交接文档-C0完成与C1对接.md
A	docs/development/开发3/开发三c0-c1交接文档.md
A	docs/testing/TEST-PR10-任务卡.md
A	docs/testing/TEST-SUMMARY-PR6-PR8.md
A	docs/testing/测试交接文档.md
M	pom.xml
A	src/main/java/org/example/timeloop/app/TimeTraceLabApplication.java
A	src/main/java/org/example/timeloop/core/FixedStepClock.java
A	src/main/java/org/example/timeloop/core/GamePhase.java
A	src/main/java/org/example/timeloop/level/model/EntitySpawnInfo.java
A	src/main/java/org/example/timeloop/level/model/Level01Footsteps.java
A	src/main/java/org/example/timeloop/level/model/LevelData.java
A	src/main/java/org/example/timeloop/level/model/PathNode.java
A	src/main/java/org/example/timeloop/level/model/TileType.java
A	src/main/java/org/example/timeloop/level/model/Vector2D.java
A	src/main/java/org/example/timeloop/mechanism/DockingPlate.java
A	src/main/java/org/example/timeloop/mechanism/DockingPlateRegistry.java
A	src/main/java/org/example/timeloop/mechanism/Door.java
A	src/main/java/org/example/timeloop/mechanism/ExitTerminal.java
A	src/main/java/org/example/timeloop/mechanism/event/EventDispatcher.java
A	src/main/java/org/example/timeloop/mechanism/event/GameEvent.java
A	src/main/java/org/example/timeloop/mechanism/event/GameObserver.java
A	src/main/java/org/example/timeloop/render/CanvasAdapter.java
A	src/main/java/org/example/timeloop/render/RenderLayer.java
A	src/main/java/org/example/timeloop/replay/AdvanceResult.java
A	src/main/java/org/example/timeloop/replay/RoundClock.java
A	src/main/java/org/example/timeloop/replay/RoundPhase.java
A	src/main/java/org/example/timeloop/replay/TickContext.java
A	src/test/java/org/example/timeloop/core/FixedStepClockTest.java
A	src/test/java/org/example/timeloop/replay/RoundClockTest.java
A	src/test/java/org/example/timeloop/replay/TickContextTest.java
